#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = ["matplotlib==3.11.2"]
# ///
"""Turn an exercise's .meta/bench/ data into figures and tables for /compare.

usage: bench_report.py <exercise-path>

Reads, when present:
  .meta/bench/scaling.jsonl              (latest run)   -> slopes + medians
  .meta/bench/pytest-benchmark.json      (Python deep)  -> mean, sd, 95% CI = mean ± 1.96·sd/√rounds
  .meta/bench/criterion/impls/*/*/new/estimates.json (Rust deep) -> criterion's mean CI and sd
  .meta/bench/gbench.json                (C++ deep)     -> mean, sd, 95% CI = mean ± 1.96·sd/√repetitions
Writes analysis/bench-tables.md and analysis/figures/{scaling,constant-factor}.png.
Every number /compare cites must come from bench-tables.md.

A speedup is claimable only if the 95% CIs are separated AND the difference in means
exceeds the larger per-call standard deviation. CI separation alone is not enough:
with thousands of rounds the CI of the mean shrinks until noise between two
identical implementations looks significant (seen in the A/A run: reference == mine).
"""

from __future__ import annotations

import json
import math
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import scaling  # noqa: E402

Z95 = 1.96
UNIT = {"ns": 1e-9, "us": 1e-6, "ms": 1e-3, "s": 1.0}


def fmt(seconds: float) -> str:
    for unit, scale in (("s", 1.0), ("ms", 1e-3), ("µs", 1e-6), ("ns", 1e-9)):
        if seconds >= scale or unit == "ns":
            return f"{seconds / scale:.3g} {unit}"
    raise AssertionError


def constant_factor(bench: Path) -> list[dict]:
    """[{impl, n, mean, lo, hi, method}] in seconds, from whichever deep-tier tool produced data."""
    rows = []
    pb = bench / "pytest-benchmark.json"
    if pb.is_file():
        for b in json.loads(pb.read_text())["benchmarks"]:
            s, params = b["stats"], b.get("params") or {}
            half = Z95 * s["stddev"] / math.sqrt(s["rounds"])
            rows.append({"impl": params["impl"], "n": int(params["n"]), "mean": s["mean"], "sd": s["stddev"],
                         "lo": s["mean"] - half, "hi": s["mean"] + half, "method": f"pytest-benchmark, {s['rounds']} rounds"})
    for est in sorted((bench / "criterion").glob("impls/*/*/new/estimates.json")):
        estimates = json.loads(est.read_text())
        mean, ci = estimates["mean"], estimates["mean"]["confidence_interval"]
        rows.append({"impl": est.parents[2].name, "n": int(est.parents[1].name), "mean": mean["point_estimate"] * 1e-9,
                     "sd": estimates["std_dev"]["point_estimate"] * 1e-9,
                     "lo": ci["lower_bound"] * 1e-9, "hi": ci["upper_bound"] * 1e-9,
                     "method": f"criterion, {ci['confidence_level']:.0%} CI"})
    gb = bench / "gbench.json"
    if gb.is_file():
        agg: dict[str, dict[str, dict]] = defaultdict(dict)
        for b in json.loads(gb.read_text())["benchmarks"]:
            if b.get("run_type") == "aggregate":
                agg[b["run_name"]][b["aggregate_name"]] = b
        for run_name, a in agg.items():
            impl, n = run_name.rsplit("/", 1)
            scale = UNIT[a["mean"]["time_unit"]]
            mean, sd, reps = a["mean"]["real_time"] * scale, a["stddev"]["real_time"] * scale, a["mean"]["repetitions"]
            half = Z95 * sd / math.sqrt(reps)
            rows.append({"impl": impl, "n": int(n), "mean": mean, "sd": sd, "lo": mean - half, "hi": mean + half,
                         "method": f"Google Benchmark, {reps} repetitions"})
    return sorted(rows, key=lambda r: (r["n"], r["impl"]))


def main() -> int:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    ex = Path(sys.argv[1]).resolve()
    bench, analysis = ex / ".meta" / "bench", ex / "analysis"
    figures = analysis / "figures"
    figures.mkdir(parents=True, exist_ok=True)

    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    md = [f"# Bench tables: {ex.name}", "",
          f"Generated by `scripts/bench_report.py` from `.meta/bench/` at {datetime.now().astimezone():%Y-%m-%d %H:%M %Z}.",
          "Every number in `comparison.md` must appear in this file.", ""]

    jsonl = bench / "scaling.jsonl"
    if jsonl.is_file():
        records = scaling.load(jsonl, "latest")
        series = scaling.medians(records)
        md += [f"## Empirical scaling (run {records[0]['run']}, {records[0]['lang']})", "",
               "| impl | points fitted | n range | slope k | R² |", "|---|---|---|---|---|"]
        fig, ax = plt.subplots(figsize=(6.4, 4.2), layout="constrained")
        for impl, pts in series.items():
            used = [(n, t) for n, t in pts if t >= 1e-5]
            (line,) = ax.plot([n for n, _ in pts], [t for _, t in pts], "o-", markersize=4, label=impl)
            if len(used) >= 3:
                k, c, r2 = scaling.fit(used)
                md.append(f"| {impl} | {len(used)} | {used[0][0]}..{used[-1][0]} | {k:.2f} | {r2:.3f} |")
                ns = [used[0][0], used[-1][0]]
                ax.plot(ns, [math.exp(c) * n**k for n in ns], "--", color=line.get_color(), alpha=0.6)
            else:
                md.append(f"| {impl} | {len(used)} | - | - | - |")
        ax.set(xscale="log", yscale="log", xlabel="n", ylabel="seconds per call (median)", title=f"{ex.name}: scaling")
        ax.legend(fontsize="small")
        fig.savefig(figures / "scaling.png", dpi=120)
        sizes = sorted({n for pts in series.values() for n, _ in pts})
        impls = list(series)
        md += ["", "![scaling](figures/scaling.png)", "", "Median seconds per call:", "",
               "| n | " + " | ".join(impls) + " |", "|---" * (len(impls) + 1) + "|"]
        lookup = {(impl, n): t for impl, pts in series.items() for n, t in pts}
        for n in sizes:
            md.append(f"| {n} | " + " | ".join(fmt(lookup[(i, n)]) if (i, n) in lookup else "-" for i in impls) + " |")
        md.append("")

    rows = constant_factor(bench)
    if rows:
        md += ["## Constant factors", "", "| impl | n | mean | 95% CI of mean | source |", "|---|---|---|---|---|"]
        md += [f"| {r['impl']} | {r['n']} | {fmt(r['mean'])} | {fmt(r['lo'])} .. {fmt(r['hi'])} | {r['method']} |"
               for r in rows]
        by_n = defaultdict(dict)
        for r in rows:
            by_n[r["n"]][r["impl"]] = r
        md += ["", "Ratios against mine (< 1 means faster than mine). *Separated*: the 95% CIs of the means do not overlap.",
               "*Beyond sd*: |Δ mean| exceeds the larger per-call standard deviation. A speedup claim needs both.", "",
               "| n | impl | mean / mine | Δ mean | larger sd | separated | beyond sd | claimable |",
               "|---|---|---|---|---|---|---|---|"]
        for n, impls_at_n in sorted(by_n.items()):
            base = impls_at_n.get("mine")
            for impl, r in sorted(impls_at_n.items()):
                if base is None or impl == "mine":
                    continue
                separated = r["hi"] < base["lo"] or r["lo"] > base["hi"]
                delta, sd = abs(r["mean"] - base["mean"]), max(r["sd"], base["sd"])
                beyond = delta > sd
                yn = {True: "yes", False: "no"}
                md.append(f"| {n} | {impl} | {r['mean'] / base['mean']:.3f} | {fmt(delta)} | {fmt(sd)} | {yn[separated]} "
                          f"| {yn[beyond]} | {yn[separated and beyond]} |")
        fig, ax = plt.subplots(figsize=(6.4, 4.2), layout="constrained")
        names = sorted({r["impl"] for r in rows})
        ns = sorted(by_n)
        width = 0.8 / len(names)
        for i, impl in enumerate(names):
            xs = [j + i * width for j, n in enumerate(ns) if impl in by_n[n]]
            rs = [by_n[n][impl] for n in ns if impl in by_n[n]]
            ax.bar(xs, [r["mean"] for r in rs], width, label=impl,
                   yerr=[[r["mean"] - r["lo"] for r in rs], [r["hi"] - r["mean"] for r in rs]], capsize=3)
        ax.set_xticks([j + width * (len(names) - 1) / 2 for j in range(len(ns))], [f"n={n}" for n in ns])
        ax.set(yscale="log", ylabel="seconds per call (mean, 95% CI)", title=f"{ex.name}: constant factors")
        ax.legend(fontsize="small")
        fig.savefig(figures / "constant-factor.png", dpi=120)
        md += ["", "![constant factors](figures/constant-factor.png)", ""]

    if not jsonl.is_file() and not rows:
        sys.exit(f"no bench data in {bench}; run `just scale` / `just bench` first")
    (analysis / "bench-tables.md").write_text("\n".join(md))
    print(f"wrote {analysis / 'bench-tables.md'} and {figures}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
